### ISSUE TITLE
Basic Authentication deprecated in JIRA Cloud

### ISSUE THREAD

**Issue by Eddie-Hartman** [rybak/jira-gource#2]
Basic authentication has been deprecated. Therefore, I could not authenticate to download issues.

See here: [https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/)

Is there an easy way to work around this?

**Comment by Eddie-Hartman** [comment]
I was able to resolve this with the API token drop-in replacement for email:password authentication. If I get time I'll make a PR to update the documentation on how to do this.

**Comment by rybak** [comment]
Thank you for letting me know about this. It seems that this only affects JIRA Cloud. Unfortunately, I don't have access to a JIRA Cloud instance to test API tokens. A pull request would be greatly appreciated.

[OAuth](https://developer.atlassian.com/server/jira/platform/oauth/) is the only other option for JIRA Server per [8.1.0 documentation](https://docs.atlassian.com/software/jira/docs/api/REST/8.1.0/), and Basic authentication is still not deprecated on JIRA Server. There's even a [Python 2 example](https://bitbucket.org/atlassianlabs/atlassian-oauth-examples/src/master/python/app.py).
